CRITICAL - 2022-12-04 06:52:54 --> Undefined variable $validation
in APPPATH\Views\unidades\nuevo.php on line 6.
 1 APPPATH\Views\unidades\nuevo.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $validation', 'APPPATH\\Views\\unidades\\nuevo.php', 6)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\unidades\\nuevo.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 5 APPPATH\Controllers\Unidades.php(28): view('unidades/nuevo', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->nuevo()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:02:00 --> syntax error, unexpected token "}"
in APPPATH\Controllers\Unidades.php on line 15.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('unidades/nuevo')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('unidades/nuevo')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('unidades/nuevo')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:06:32 --> syntax error, unexpected identifier "value", expecting "," or ";"
in APPPATH\Views\unidades\nuevo.php on line 17.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 3 APPPATH\Controllers\Unidades.php(32): view('unidades/nuevo', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->nuevo()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:06:51 --> syntax error, unexpected identifier "value", expecting "," or ";"
in APPPATH\Views\unidades\nuevo.php on line 17.
 1 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 3 APPPATH\Controllers\Unidades.php(32): view('unidades/nuevo', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->nuevo()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:14:42 --> Object of type CodeIgniter\Validation\Validation is not callable
in APPPATH\Views\unidades\nuevo.php on line 7.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 4 APPPATH\Controllers\Unidades.php(61): view('unidades/nuevo', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->insertar()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:18:48 --> Object of type CodeIgniter\Validation\Validation is not callable
in APPPATH\Views\unidades\nuevo.php on line 8.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 4 APPPATH\Controllers\Unidades.php(61): view('unidades/nuevo', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->insertar()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:18:53 --> Object of type CodeIgniter\Validation\Validation is not callable
in APPPATH\Views\unidades\nuevo.php on line 8.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 4 APPPATH\Controllers\Unidades.php(61): view('unidades/nuevo', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->insertar()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:19:13 --> Object of type CodeIgniter\Validation\Validation is not callable
in APPPATH\Views\unidades\nuevo.php on line 8.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 4 APPPATH\Controllers\Unidades.php(61): view('unidades/nuevo', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->insertar()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:23:38 --> Object of type CodeIgniter\Validation\Validation is not callable
in APPPATH\Views\unidades\nuevo.php on line 8.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/nuevo', [], true)
 4 APPPATH\Controllers\Unidades.php(61): view('unidades/nuevo', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->insertar()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:30:05 --> Unclosed '{' on line 10 does not match ']'
in APPPATH\Controllers\Unidades.php on line 23.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('unidades/insertar')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('unidades/insertar')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('unidades/insertar')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:47:53 --> Trying to access array offset on value of type null
in APPPATH\Views\unidades\editar.php on line 14.
 1 APPPATH\Views\unidades\editar.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\unidades\\editar.php', 14)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\unidades\\editar.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('unidades/editar', [], true)
 5 APPPATH\Controllers\Unidades.php(76): view('unidades/editar', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->editar('4')
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 07:48:23 --> Too few arguments to function App\Controllers\Unidades::editar(), 0 passed in C:\xampp\htdocs\posn\system\CodeIgniter.php on line 927 and at least 1 expected
in APPPATH\Controllers\Unidades.php on line 64.
 1 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Unidades->editar()
 2 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unidades))
 3 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 07:59:29 --> mysqli_sql_exception: Duplicate entry '12345688' for key 'codigo' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\posn\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\posn\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\posn\app\Controllers\Productos.php(50): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Productos->insertar()
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#11 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-04 07:59:29 --> Duplicate entry '12345688' for key 'codigo'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'1\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 07:59:29\', \'2022-12-04 07:59:29\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'1\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 07:59:29\', \'2022-12-04 07:59:29\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'1\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 07:59:29\', \'2022-12-04 07:59:29\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (:codigo:, :nombre:, :precio_venta:, :precio_compra:, :stock_minimo:, :inventariable:, :id_unidad:, :id_categoria:, :fecha_alta:, :fecha_edit:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Productos.php(50): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Productos->insertar()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 08:08:41 --> mysqli_sql_exception: Duplicate entry '12345688' for key 'codigo' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `pr...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `pr...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `pr...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `pr...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(749): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\posn\system\Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\posn\system\BaseModel.php(659): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\posn\app\Controllers\Productos.php(69): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Productos->insertar()
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
#11 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2022-12-04 08:08:41 --> Duplicate entry '12345688' for key 'codigo'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'2\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 08:08:41\', \'2022-12-04 08:08:41\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'2\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 08:08:41\', \'2022-12-04 08:08:41\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (\'12345688\', \'2\', \'2\', \'3\', \'4\', \'1\', \'1\', \'5\', \'2022-12-04 08:08:41\', \'2022-12-04 08:08:41\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `productos` (`codigo`, `nombre`, `precio_venta`, `precio_compra`, `stock_minimo`, `inventariable`, `id_unidad`, `id_categoria`, `fecha_alta`, `fecha_edit`) VALUES (:codigo:, :nombre:, :precio_venta:, :precio_compra:, :stock_minimo:, :inventariable:, :id_unidad:, :id_categoria:, :fecha_alta:, :fecha_edit:)', [...], false)
 5 SYSTEMPATH\Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(749): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(659): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Productos.php(69): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Productos->insertar()
11 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
12 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 08:10:40 --> Undefined variable $unidades
in APPPATH\Views\productos\nuevo.php on line 34.
 1 APPPATH\Views\productos\nuevo.php(34): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $unidades', 'APPPATH\\Views\\productos\\nuevo.php', 34)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\productos\\nuevo.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('productos/nuevo', [], true)
 5 APPPATH\Controllers\Productos.php(76): view('productos/nuevo', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Productos->insertar()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Productos))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 09:15:05 --> Undefined property: App\Controllers\Clientes::$unidades
in APPPATH\Controllers\Clientes.php on line 44.
 1 APPPATH\Controllers\Clientes.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Clientes::$unidades', 'APPPATH\\Controllers\\Clientes.php', 44)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Clientes->nuevo()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 09:23:30 --> syntax error, unexpected token "return", expecting "]"
in APPPATH\Controllers\Clientes.php on line 53.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('clientes/nuevo')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('clientes/nuevo')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('clientes/nuevo')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 09:23:39 --> syntax error, unexpected token "return", expecting "]"
in APPPATH\Controllers\Clientes.php on line 53.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('clientes')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('clientes')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('clientes')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 09:23:46 --> syntax error, unexpected token "return", expecting "]"
in APPPATH\Controllers\Clientes.php on line 53.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('clientes')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('clientes')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('clientes')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 09:32:02 --> Undefined property: App\Controllers\Clientes::$unidades
in APPPATH\Controllers\Clientes.php on line 64.
 1 APPPATH\Controllers\Clientes.php(64): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Clientes::$unidades', 'APPPATH\\Controllers\\Clientes.php', 64)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Clientes->editar('1')
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Clientes))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 11:32:31 --> syntax error, unexpected token ";", expecting ")"
in APPPATH\Controllers\Configuracion.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('configuracion')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('configuracion')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('configuracion')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 11:32:37 --> syntax error, unexpected token ";", expecting ")"
in APPPATH\Controllers\Configuracion.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('configuracion')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('configuracion')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('configuracion')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 11:33:23 --> syntax error, unexpected token ";", expecting ")"
in APPPATH\Controllers\Configuracion.php on line 37.
 1 SYSTEMPATH\Router\Router.php(499): CodeIgniter\Router\AutoRouter->getRoute('configuracion')
 2 SYSTEMPATH\Router\Router.php(205): CodeIgniter\Router\Router->autoRoute('configuracion')
 3 SYSTEMPATH\CodeIgniter.php(802): CodeIgniter\Router\Router->handle('configuracion')
 4 SYSTEMPATH\CodeIgniter.php(430): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-12-04 12:12:04 --> Undefined variable $tienda_rfc
in APPPATH\Controllers\Configuracion.php on line 39.
 1 APPPATH\Controllers\Configuracion.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $tienda_rfc', 'APPPATH\\Controllers\\Configuracion.php', 39)
 2 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->index()
 3 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
 4 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 13:45:40 --> mysqli_sql_exception: Unknown column 'fecha_edit' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(50): CodeIgniter\Model->update(Array, Array)
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 13:45:40 --> Unknown column 'fecha_edit' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:40\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:40\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:40\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `fecha_edit` = :fecha_edit:
WHERE `configuracion`.`id` IN :configuracion.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Configuracion.php(50): CodeIgniter\Model->update([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 13:45:52 --> mysqli_sql_exception: Unknown column 'fecha_edit' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(50): CodeIgniter\Model->update(Array, Array)
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 13:45:52 --> Unknown column 'fecha_edit' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:52\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:52\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP1\', `fecha_edit` = \'2022-12-04 13:45:52\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `fecha_edit` = :fecha_edit:
WHERE `configuracion`.`id` IN :configuracion.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Configuracion.php(50): CodeIgniter\Model->update([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 13:46:12 --> mysqli_sql_exception: Unknown column 'fecha_edit' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(50): CodeIgniter\Model->update(Array, Array)
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 13:46:12 --> Unknown column 'fecha_edit' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:12\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:12\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:12\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `fecha_edit` = :fecha_edit:
WHERE `configuracion`.`id` IN :configuracion.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Configuracion.php(50): CodeIgniter\Model->update([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 13:46:31 --> mysqli_sql_exception: Unknown column 'fecha_edit' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(50): CodeIgniter\Model->update(Array, Array)
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 13:46:31 --> Unknown column 'fecha_edit' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:31\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:31\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:46:31\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `fecha_edit` = :fecha_edit:
WHERE `configuracion`.`id` IN :configuracion.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Configuracion.php(50): CodeIgniter\Model->update([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 13:47:27 --> mysqli_sql_exception: Unknown column 'fecha_edit' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(50): CodeIgniter\Model->update(Array, Array)
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 13:47:27 --> Unknown column 'fecha_edit' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:47:27\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:47:27\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 1\', `fecha_edit` = \'2022-12-04 13:47:27\'
WHERE `configuracion`.`id` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `fecha_edit` = :fecha_edit:
WHERE `configuracion`.`id` IN :configuracion.id:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Configuracion.php(50): CodeIgniter\Model->update([...], [...])
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 14:17:28 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 14:17:28 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 15\', `updated_at` = \'2022-12-04 14:17:28\'
WHERE `nombre` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 15\', `updated_at` = \'2022-12-04 14:17:28\'
WHERE `nombre` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 15\', `updated_at` = \'2022-12-04 14:17:28\'
WHERE `nombre` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `updated_at` = :updated_at:
WHERE `nombre` IN :nombre:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate(null, [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(null, [...])
 8 APPPATH\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 14:20:16 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 14:20:16 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 3\', `updated_at` = \'2022-12-04 14:20:16\'
WHERE `nombre` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 3\', `updated_at` = \'2022-12-04 14:20:16\'
WHERE `nombre` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 3\', `updated_at` = \'2022-12-04 14:20:16\'
WHERE `nombre` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `updated_at` = :updated_at:
WHERE `nombre` IN :nombre:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate(null, [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(null, [...])
 8 APPPATH\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-12-04 14:20:28 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\posn\system\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configu...', 0)
#1 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configu...')
#2 C:\xampp\htdocs\posn\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configu...')
#3 C:\xampp\htdocs\posn\system\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configu...', Array, false)
#4 C:\xampp\htdocs\posn\system\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\posn\system\BaseModel.php(886): CodeIgniter\Model->doUpdate(NULL, Array)
#6 C:\xampp\htdocs\posn\system\Model.php(693): CodeIgniter\BaseModel->update(NULL, Array)
#7 C:\xampp\htdocs\posn\app\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
#8 C:\xampp\htdocs\posn\system\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
#9 C:\xampp\htdocs\posn\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
#10 C:\xampp\htdocs\posn\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\posn\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-12-04 14:20:28 --> Unknown column 'updated_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('UPDATE `configuracion` SET `valor` = \'Tienda CDP 41\', `updated_at` = \'2022-12-04 14:20:28\'
WHERE `nombre` IN (\'tienda_nombre\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `configuracion` SET `valor` = \'Tienda CDP 41\', `updated_at` = \'2022-12-04 14:20:28\'
WHERE `nombre` IN (\'tienda_nombre\')')
 3 SYSTEMPATH\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `configuracion` SET `valor` = \'Tienda CDP 41\', `updated_at` = \'2022-12-04 14:20:28\'
WHERE `nombre` IN (\'tienda_nombre\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2079): CodeIgniter\Database\BaseConnection->query('UPDATE `configuracion` SET `valor` = :valor:, `updated_at` = :updated_at:
WHERE `nombre` IN :nombre:', [...], false)
 5 SYSTEMPATH\Model.php(338): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(886): CodeIgniter\Model->doUpdate(null, [...])
 7 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(null, [...])
 8 APPPATH\Controllers\Configuracion.php(51): CodeIgniter\Model->update()
 9 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Configuracion->actualizar()
10 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion))
11 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
